"""Tests for AI detection."""

import pytest

from git_aiblame.detector import AIDetector


@pytest.fixture
def detector():
    """Create a detector instance."""
    return AIDetector()


class TestAIDetector:
    """Test AI detection functionality."""

    def test_detect_claude(self, detector):
        """Test detection of Claude mentions."""
        assert detector.detect("Co-Authored-By: Claude") == "claude"
        assert detector.detect("co-authored-by: claude code") == "claude"
        assert detector.detect("Generated by Claude") == "claude"
        assert detector.detect("[claude] add feature") == "claude"

    def test_detect_copilot(self, detector):
        """Test detection of Copilot mentions."""
        assert detector.detect("Co-Authored-By: GitHub Copilot") == "copilot"
        assert detector.detect("Generated by Copilot") == "copilot"
        assert detector.detect("[copilot] fix bug") == "copilot"

    def test_detect_gpt(self, detector):
        """Test detection of GPT mentions."""
        assert detector.detect("Co-Authored-By: GPT-4") == "gpt"
        assert detector.detect("Generated by GPT") == "gpt"
        assert detector.detect("[gpt] refactor") == "gpt"

    def test_detect_generic_ai(self, detector):
        """Test detection of generic AI mentions."""
        assert detector.detect("AI generated code") == "ai"
        assert detector.detect("AI-assisted commit") == "ai"
        assert detector.detect("[ai] update") == "ai"

    def test_no_detection(self, detector):
        """Test that human commits return None."""
        assert detector.detect("Regular commit") is None
        assert detector.detect("Fix bug in parser") is None
        assert detector.detect("Add new feature") is None

    def test_is_ai_assisted(self, detector):
        """Test AI assistance flag."""
        assert detector.is_ai_assisted("Co-Authored-By: Claude")
        assert not detector.is_ai_assisted("Regular commit")

    def test_parse_commit_message(self, detector):
        """Test commit message parsing."""
        result = detector.parse_commit_message("Co-Authored-By: Claude")
        assert result["ai_type"] == "claude"
        assert result["is_ai"] is True

        result = detector.parse_commit_message("Regular commit")
        assert result["ai_type"] is None
        assert result["is_ai"] is False
