"""Configuration constants for git-aiblame."""

AI_PATTERNS = {
    "claude": [
        r"(?i)co-authored-by:\s*claude",
        r"(?i)co-authored-by:\s*claude\s+code",
        r"(?i)generated by claude",
        r"(?i)\[claude\]",
    ],
    "copilot": [
        r"(?i)co-authored-by:\s*github\s+copilot",
        r"(?i)co-authored-by:\s*copilot",
        r"(?i)generated by copilot",
        r"(?i)\[copilot\]",
    ],
    "gpt": [
        r"(?i)co-authored-by:\s*gpt",
        r"(?i)generated by gpt",
        r"(?i)\[gpt\]",
    ],
    "ai": [
        r"(?i)ai\s+generated",
        r"(?i)ai-generated",
        r"(?i)ai\s+assisted",
        r"(?i)\[ai\]",
    ],
}
